/* =====================================================================
   DATA ASMAUL HUSNA (99 nama Allah) — tampil di asmaul-husna.html
   =====================================================================
   Setiap baris: { n: nomor, ar: tulisan Arab, latin: bacaan Latin, arti: arti }
   Untuk mengubah arti atau ejaan Latin, cukup edit teksnya lalu commit.
   Daftar mengikuti urutan yang lazim dipakai di Indonesia.
   ===================================================================== */

window.GRADIEND_ASMAUL_HUSNA = [
  { n: 1,  ar: "الرَّحْمَنُ", latin: "Ar-Rahman", arti: "Yang Maha Pengasih" },
  { n: 2,  ar: "الرَّحِيمُ", latin: "Ar-Rahim", arti: "Yang Maha Penyayang" },
  { n: 3,  ar: "الْمَلِكُ", latin: "Al-Malik", arti: "Yang Maha Merajai" },
  { n: 4,  ar: "الْقُدُّوسُ", latin: "Al-Quddus", arti: "Yang Maha Suci" },
  { n: 5,  ar: "السَّلَامُ", latin: "As-Salam", arti: "Yang Maha Memberi Keselamatan" },
  { n: 6,  ar: "الْمُؤْمِنُ", latin: "Al-Mu'min", arti: "Yang Maha Memberi Rasa Aman" },
  { n: 7,  ar: "الْمُهَيْمِنُ", latin: "Al-Muhaimin", arti: "Yang Maha Memelihara Keselamatan" },
  { n: 8,  ar: "الْعَزِيزُ", latin: "Al-'Aziz", arti: "Yang Maha Perkasa" },
  { n: 9,  ar: "الْجَبَّارُ", latin: "Al-Jabbar", arti: "Yang Maha Memaksa" },
  { n: 10, ar: "الْمُتَكَبِّرُ", latin: "Al-Mutakabbir", arti: "Yang Maha Megah" },
  { n: 11, ar: "الْخَالِقُ", latin: "Al-Khaliq", arti: "Yang Maha Pencipta" },
  { n: 12, ar: "الْبَارِئُ", latin: "Al-Bari'", arti: "Yang Maha Mengadakan" },
  { n: 13, ar: "الْمُصَوِّرُ", latin: "Al-Mushawwir", arti: "Yang Maha Membentuk Rupa" },
  { n: 14, ar: "الْغَفَّارُ", latin: "Al-Ghaffar", arti: "Yang Maha Pengampun" },
  { n: 15, ar: "الْقَهَّارُ", latin: "Al-Qahhar", arti: "Yang Maha Menundukkan" },
  { n: 16, ar: "الْوَهَّابُ", latin: "Al-Wahhab", arti: "Yang Maha Pemberi Karunia" },
  { n: 17, ar: "الرَّزَّاقُ", latin: "Ar-Razzaq", arti: "Yang Maha Pemberi Rezeki" },
  { n: 18, ar: "الْفَتَّاحُ", latin: "Al-Fattah", arti: "Yang Maha Pembuka" },
  { n: 19, ar: "الْعَلِيمُ", latin: "Al-'Alim", arti: "Yang Maha Mengetahui" },
  { n: 20, ar: "الْقَابِضُ", latin: "Al-Qabidh", arti: "Yang Maha Menyempitkan" },
  { n: 21, ar: "الْبَاسِطُ", latin: "Al-Basith", arti: "Yang Maha Melapangkan" },
  { n: 22, ar: "الْخَافِضُ", latin: "Al-Khafidh", arti: "Yang Maha Merendahkan" },
  { n: 23, ar: "الرَّافِعُ", latin: "Ar-Rafi'", arti: "Yang Maha Meninggikan" },
  { n: 24, ar: "الْمُعِزُّ", latin: "Al-Mu'izz", arti: "Yang Maha Memuliakan" },
  { n: 25, ar: "الْمُذِلُّ", latin: "Al-Mudzill", arti: "Yang Maha Menghinakan" },
  { n: 26, ar: "السَّمِيعُ", latin: "As-Sami'", arti: "Yang Maha Mendengar" },
  { n: 27, ar: "الْبَصِيرُ", latin: "Al-Bashir", arti: "Yang Maha Melihat" },
  { n: 28, ar: "الْحَكَمُ", latin: "Al-Hakam", arti: "Yang Maha Menetapkan Hukum" },
  { n: 29, ar: "الْعَدْلُ", latin: "Al-'Adl", arti: "Yang Maha Adil" },
  { n: 30, ar: "اللَّطِيفُ", latin: "Al-Lathif", arti: "Yang Maha Lembut" },
  { n: 31, ar: "الْخَبِيرُ", latin: "Al-Khabir", arti: "Yang Maha Mengetahui Secara Mendalam" },
  { n: 32, ar: "الْحَلِيمُ", latin: "Al-Halim", arti: "Yang Maha Penyantun" },
  { n: 33, ar: "الْعَظِيمُ", latin: "Al-'Azhim", arti: "Yang Maha Agung" },
  { n: 34, ar: "الْغَفُورُ", latin: "Al-Ghafur", arti: "Yang Maha Pengampun" },
  { n: 35, ar: "الشَّكُورُ", latin: "Asy-Syakur", arti: "Yang Maha Mensyukuri" },
  { n: 36, ar: "الْعَلِيُّ", latin: "Al-'Aliyy", arti: "Yang Maha Tinggi" },
  { n: 37, ar: "الْكَبِيرُ", latin: "Al-Kabir", arti: "Yang Maha Besar" },
  { n: 38, ar: "الْحَفِيظُ", latin: "Al-Hafizh", arti: "Yang Maha Menjaga" },
  { n: 39, ar: "الْمُقِيتُ", latin: "Al-Muqit", arti: "Yang Maha Pemberi Kecukupan" },
  { n: 40, ar: "الْحَسِيبُ", latin: "Al-Hasib", arti: "Yang Maha Membuat Perhitungan" },
  { n: 41, ar: "الْجَلِيلُ", latin: "Al-Jalil", arti: "Yang Maha Luhur" },
  { n: 42, ar: "الْكَرِيمُ", latin: "Al-Karim", arti: "Yang Maha Pemurah" },
  { n: 43, ar: "الرَّقِيبُ", latin: "Ar-Raqib", arti: "Yang Maha Mengawasi" },
  { n: 44, ar: "الْمُجِيبُ", latin: "Al-Mujib", arti: "Yang Maha Mengabulkan" },
  { n: 45, ar: "الْوَاسِعُ", latin: "Al-Wasi'", arti: "Yang Maha Luas" },
  { n: 46, ar: "الْحَكِيمُ", latin: "Al-Hakim", arti: "Yang Maha Bijaksana" },
  { n: 47, ar: "الْوَدُودُ", latin: "Al-Wadud", arti: "Yang Maha Mencintai" },
  { n: 48, ar: "الْمَجِيدُ", latin: "Al-Majid", arti: "Yang Maha Mulia" },
  { n: 49, ar: "الْبَاعِثُ", latin: "Al-Ba'its", arti: "Yang Maha Membangkitkan" },
  { n: 50, ar: "الشَّهِيدُ", latin: "Asy-Syahid", arti: "Yang Maha Menyaksikan" },
  { n: 51, ar: "الْحَقُّ", latin: "Al-Haqq", arti: "Yang Maha Benar" },
  { n: 52, ar: "الْوَكِيلُ", latin: "Al-Wakil", arti: "Yang Maha Memelihara Urusan" },
  { n: 53, ar: "الْقَوِيُّ", latin: "Al-Qawiyy", arti: "Yang Maha Kuat" },
  { n: 54, ar: "الْمَتِينُ", latin: "Al-Matin", arti: "Yang Maha Kokoh" },
  { n: 55, ar: "الْوَلِيُّ", latin: "Al-Waliyy", arti: "Yang Maha Melindungi" },
  { n: 56, ar: "الْحَمِيدُ", latin: "Al-Hamid", arti: "Yang Maha Terpuji" },
  { n: 57, ar: "الْمُحْصِي", latin: "Al-Muhshi", arti: "Yang Maha Menghitung" },
  { n: 58, ar: "الْمُبْدِئُ", latin: "Al-Mubdi'", arti: "Yang Maha Memulai" },
  { n: 59, ar: "الْمُعِيدُ", latin: "Al-Mu'id", arti: "Yang Maha Mengembalikan" },
  { n: 60, ar: "الْمُحْيِي", latin: "Al-Muhyi", arti: "Yang Maha Menghidupkan" },
  { n: 61, ar: "الْمُمِيتُ", latin: "Al-Mumit", arti: "Yang Maha Mematikan" },
  { n: 62, ar: "الْحَيُّ", latin: "Al-Hayy", arti: "Yang Maha Hidup" },
  { n: 63, ar: "الْقَيُّومُ", latin: "Al-Qayyum", arti: "Yang Maha Berdiri Sendiri" },
  { n: 64, ar: "الْوَاجِدُ", latin: "Al-Wajid", arti: "Yang Maha Menemukan" },
  { n: 65, ar: "الْمَاجِدُ", latin: "Al-Maajid", arti: "Yang Maha Mulia" },
  { n: 66, ar: "الْوَاحِدُ", latin: "Al-Wahid", arti: "Yang Maha Esa" },
  { n: 67, ar: "الْأَحَدُ", latin: "Al-Ahad", arti: "Yang Maha Tunggal" },
  { n: 68, ar: "الصَّمَدُ", latin: "Ash-Shamad", arti: "Yang Maha Menjadi Tempat Bergantung" },
  { n: 69, ar: "الْقَادِرُ", latin: "Al-Qadir", arti: "Yang Maha Kuasa" },
  { n: 70, ar: "الْمُقْتَدِرُ", latin: "Al-Muqtadir", arti: "Yang Maha Berkuasa" },
  { n: 71, ar: "الْمُقَدِّمُ", latin: "Al-Muqaddim", arti: "Yang Maha Mendahulukan" },
  { n: 72, ar: "الْمُؤَخِّرُ", latin: "Al-Mu'akhkhir", arti: "Yang Maha Mengakhirkan" },
  { n: 73, ar: "الْأَوَّلُ", latin: "Al-Awwal", arti: "Yang Maha Awal" },
  { n: 74, ar: "الْآخِرُ", latin: "Al-Akhir", arti: "Yang Maha Akhir" },
  { n: 75, ar: "الظَّاهِرُ", latin: "Azh-Zhahir", arti: "Yang Maha Nyata" },
  { n: 76, ar: "الْبَاطِنُ", latin: "Al-Bathin", arti: "Yang Maha Tersembunyi" },
  { n: 77, ar: "الْوَالِي", latin: "Al-Wali", arti: "Yang Maha Memerintah" },
  { n: 78, ar: "الْمُتَعَالِي", latin: "Al-Muta'ali", arti: "Yang Maha Tinggi" },
  { n: 79, ar: "الْبَرُّ", latin: "Al-Barr", arti: "Yang Maha Dermawan" },
  { n: 80, ar: "التَّوَّابُ", latin: "At-Tawwab", arti: "Yang Maha Penerima Tobat" },
  { n: 81, ar: "الْمُنْتَقِمُ", latin: "Al-Muntaqim", arti: "Yang Maha Memberi Balasan" },
  { n: 82, ar: "الْعَفُوُّ", latin: "Al-'Afuww", arti: "Yang Maha Pemaaf" },
  { n: 83, ar: "الرَّءُوفُ", latin: "Ar-Ra'uf", arti: "Yang Maha Penyantun" },
  { n: 84, ar: "مَالِكُ الْمُلْكِ", latin: "Malikul Mulk", arti: "Yang Maha Menguasai Kerajaan" },
  { n: 85, ar: "ذُو الْجَلَالِ وَالْإِكْرَامِ", latin: "Dzul Jalali wal Ikram", arti: "Yang Memiliki Kebesaran dan Kemuliaan" },
  { n: 86, ar: "الْمُقْسِطُ", latin: "Al-Muqsith", arti: "Yang Maha Adil" },
  { n: 87, ar: "الْجَامِعُ", latin: "Al-Jami'", arti: "Yang Maha Mengumpulkan" },
  { n: 88, ar: "الْغَنِيُّ", latin: "Al-Ghaniyy", arti: "Yang Maha Kaya" },
  { n: 89, ar: "الْمُغْنِي", latin: "Al-Mughni", arti: "Yang Maha Memberi Kekayaan" },
  { n: 90, ar: "الْمَانِعُ", latin: "Al-Mani'", arti: "Yang Maha Mencegah" },
  { n: 91, ar: "الضَّارُّ", latin: "Adh-Dharr", arti: "Yang Maha Memberi Mudarat" },
  { n: 92, ar: "النَّافِعُ", latin: "An-Nafi'", arti: "Yang Maha Memberi Manfaat" },
  { n: 93, ar: "النُّورُ", latin: "An-Nur", arti: "Yang Maha Bercahaya" },
  { n: 94, ar: "الْهَادِي", latin: "Al-Hadi", arti: "Yang Maha Memberi Petunjuk" },
  { n: 95, ar: "الْبَدِيعُ", latin: "Al-Badi'", arti: "Yang Maha Pencipta Tanpa Contoh" },
  { n: 96, ar: "الْبَاقِي", latin: "Al-Baqi", arti: "Yang Maha Kekal" },
  { n: 97, ar: "الْوَارِثُ", latin: "Al-Warits", arti: "Yang Maha Mewarisi" },
  { n: 98, ar: "الرَّشِيدُ", latin: "Ar-Rasyid", arti: "Yang Maha Membimbing" },
  { n: 99, ar: "الصَّبُورُ", latin: "Ash-Shabur", arti: "Yang Maha Sabar" }
];
