/* =====================================================================
   DATA DOA-DOA — tampil di doa.html
   =====================================================================
   Setiap doa: { kat, judul, ar, latin, arti, sumber, catatan(opsional) }
   kat harus salah satu nama di DOA_KATEGORI di bawah.
   Tambah doa dengan menyalin satu blok lalu mengisinya.
   Pastikan teks Arab, sumber, dan terjemahan benar sebelum menambah.
   ===================================================================== */

window.GRADIEND_DOA_KATEGORI = [
  { id: "harian", nama: "Harian", ikon: "fa-sun" },
  { id: "ibadah", nama: "Ibadah", ikon: "fa-mosque" },
  { id: "perlindungan", nama: "Perlindungan", ikon: "fa-shield-halved" },
  { id: "ilmu", nama: "Ilmu dan Hati", ikon: "fa-book-open" },
  { id: "keluarga", nama: "Keluarga", ikon: "fa-people-roof" },
  { id: "ampunan", nama: "Taubat dan Ampunan", ikon: "fa-hands-praying" },
  { id: "kesulitan", nama: "Kesulitan dan Sakit", ikon: "fa-heart-pulse" }
];

window.GRADIEND_DOA = [

  /* ---------- Harian ---------- */
  { kat: "harian", judul: "Bangun Tidur",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    latin: "Alhamdu lillahil-ladzi ahyana ba'da ma amatana wa ilaihin-nusyur.",
    arti: "Segala puji bagi Allah yang telah menghidupkan kami setelah mematikan kami (tidur), dan kepada-Nya kami akan dikembalikan.",
    sumber: "HR. Bukhari" },
  { kat: "harian", judul: "Sebelum Tidur",
    ar: "بِاسْمِكَ اللَّهُمَّ أَحْيَا وَبِاسْمِكَ أَمُوتُ",
    latin: "Bismikallahumma ahya wa bismika amut.",
    arti: "Dengan menyebut nama-Mu ya Allah, aku hidup dan aku mati.",
    sumber: "HR. Bukhari" },
  { kat: "harian", judul: "Sebelum Makan",
    ar: "بِسْمِ اللَّهِ",
    latin: "Bismillah.",
    arti: "Dengan menyebut nama Allah.",
    sumber: "HR. Bukhari dan Muslim",
    catatan: "Jika lupa membacanya di awal, ucapkan: بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ (Bismillahi awwalahu wa akhirah), artinya “Dengan nama Allah di awal dan di akhirnya” (HR. Abu Dawud dan Tirmidzi)." },
  { kat: "harian", judul: "Sesudah Makan",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    latin: "Alhamdu lillahil-ladzi ath'amana wa saqana wa ja'alana muslimin.",
    arti: "Segala puji bagi Allah yang telah memberi kami makan dan minum serta menjadikan kami orang-orang Muslim.",
    sumber: "HR. Abu Dawud dan Tirmidzi" },
  { kat: "harian", judul: "Berbuka Puasa",
    ar: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
    latin: "Dzahabazh-zhama'u wabtallatil-'uruqu wa tsabatal-ajru insya Allah.",
    arti: "Telah hilang rasa haus, urat-urat telah basah, dan pahala telah tetap, insya Allah.",
    sumber: "HR. Abu Dawud" },
  { kat: "harian", judul: "Masuk Kamar Mandi",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    latin: "Allahumma inni a'udzu bika minal-khubutsi wal-khaba'its.",
    arti: "Ya Allah, aku berlindung kepada-Mu dari setan laki-laki dan setan perempuan.",
    sumber: "HR. Bukhari dan Muslim" },
  { kat: "harian", judul: "Keluar Kamar Mandi",
    ar: "غُفْرَانَكَ",
    latin: "Ghufranaka.",
    arti: "Aku memohon ampunan-Mu.",
    sumber: "HR. Abu Dawud, Tirmidzi, dan Ibnu Majah" },
  { kat: "harian", judul: "Keluar Rumah",
    ar: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    latin: "Bismillah, tawakkaltu 'alallah, wa la haula wa la quwwata illa billah.",
    arti: "Dengan nama Allah, aku bertawakal kepada Allah. Tidak ada daya dan kekuatan kecuali dengan pertolongan Allah.",
    sumber: "HR. Abu Dawud dan Tirmidzi" },
  { kat: "harian", judul: "Naik Kendaraan",
    ar: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ",
    latin: "Subhanal-ladzi sakhkhara lana hadza wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun.",
    arti: "Mahasuci Tuhan yang telah menundukkan semua ini bagi kami, padahal kami sebelumnya tidak mampu menguasainya, dan sesungguhnya kepada Tuhan kamilah kami akan kembali.",
    sumber: "QS. Az-Zukhruf: 13-14" },
  { kat: "harian", judul: "Ketika Turun Hujan",
    ar: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    latin: "Allahumma shayyiban nafi'a.",
    arti: "Ya Allah, jadikanlah hujan ini hujan yang bermanfaat.",
    sumber: "HR. Bukhari" },
  { kat: "harian", judul: "Ketika Bersin",
    ar: "الْحَمْدُ لِلَّهِ",
    latin: "Alhamdulillah.",
    arti: "Segala puji bagi Allah.",
    sumber: "HR. Bukhari",
    catatan: "Orang yang mendengar menjawab: يَرْحَمُكَ اللَّهُ (Yarhamukallah), artinya “Semoga Allah merahmatimu”. Yang bersin membalas: يَهْدِيكُمُ اللَّهُ وَيُصْلِحُ بَالَكُمْ (Yahdikumullahu wa yushlihu balakum), artinya “Semoga Allah memberi petunjuk kepadamu dan memperbaiki keadaanmu”." },
  { kat: "harian", judul: "Memperbaiki Akhlak",
    ar: "اللَّهُمَّ أَحْسَنْتَ خَلْقِي فَأَحْسِنْ خُلُقِي",
    latin: "Allahumma ahsanta khalqi fa ahsin khuluqi.",
    arti: "Ya Allah, Engkau telah memperbagus rupaku, maka perbagus pula akhlakku.",
    sumber: "HR. Ahmad" },

  /* ---------- Ibadah ---------- */
  { kat: "ibadah", judul: "Sesudah Wudu",
    ar: "أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    latin: "Asyhadu an la ilaha illallahu wahdahu la syarika lah, wa asyhadu anna Muhammadan 'abduhu wa rasuluh.",
    arti: "Aku bersaksi bahwa tidak ada tuhan yang berhak disembah selain Allah semata, tiada sekutu bagi-Nya, dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya.",
    sumber: "HR. Muslim" },
  { kat: "ibadah", judul: "Masuk Masjid",
    ar: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    latin: "Allahummaf-tah li abwaba rahmatik.",
    arti: "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.",
    sumber: "HR. Muslim",
    catatan: "Masuk dengan kaki kanan lebih dahulu." },
  { kat: "ibadah", judul: "Keluar Masjid",
    ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    latin: "Allahumma inni as'aluka min fadhlik.",
    arti: "Ya Allah, sesungguhnya aku memohon kepada-Mu sebagian dari karunia-Mu.",
    sumber: "HR. Muslim",
    catatan: "Keluar dengan kaki kiri lebih dahulu." },
  { kat: "ibadah", judul: "Sesudah Azan",
    ar: "اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
    latin: "Allahumma rabba hadzihid-da'watit-tammah, wash-shalatil-qa'imah, ati Muhammadanil-wasilata wal-fadhilah, wab'atshu maqamam mahmudanil-ladzi wa'adtah.",
    arti: "Ya Allah, Tuhan pemilik seruan yang sempurna ini dan salat yang akan ditegakkan, berikanlah kepada Nabi Muhammad wasilah (kedudukan tinggi) dan keutamaan, dan bangkitkanlah beliau pada kedudukan terpuji yang telah Engkau janjikan.",
    sumber: "HR. Bukhari" },

  /* ---------- Perlindungan ---------- */
  { kat: "perlindungan", judul: "Perlindungan Pagi dan Petang",
    ar: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    latin: "Bismillahil-ladzi la yadhurru ma'asmihi syai'un fil-ardhi wa la fis-sama'i wa huwas-sami'ul-'alim.",
    arti: "Dengan nama Allah yang bersama nama-Nya tidak ada sesuatu pun di bumi maupun di langit yang dapat membahayakan, dan Dia Maha Mendengar lagi Maha Mengetahui.",
    sumber: "HR. Abu Dawud dan Tirmidzi",
    catatan: "Dibaca tiga kali di pagi dan petang hari." },
  { kat: "perlindungan", judul: "Ridha Allah sebagai Tuhan",
    ar: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ نَبِيًّا",
    latin: "Radhitu billahi rabba, wa bil-islami dina, wa bi Muhammadin nabiyya.",
    arti: "Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad sebagai nabiku.",
    sumber: "HR. Abu Dawud dan Tirmidzi",
    catatan: "Dibaca tiga kali di pagi dan petang hari." },
  { kat: "perlindungan", judul: "Hasbunallah",
    ar: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    latin: "Hasbunallahu wa ni'mal-wakil.",
    arti: "Cukuplah Allah bagi kami, dan Dia sebaik-baik pelindung.",
    sumber: "QS. Ali 'Imran: 173" },
  { kat: "perlindungan", judul: "Berlindung dari Kesedihan dan Kelemahan",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    latin: "Allahumma inni a'udzu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dhala'id-daini wa ghalabatir-rijal.",
    arti: "Ya Allah, aku berlindung kepada-Mu dari rasa gelisah dan sedih, dari lemah dan malas, dari kikir dan pengecut, dari lilitan utang dan penindasan orang lain.",
    sumber: "HR. Bukhari" },

  /* ---------- Ilmu dan Hati ---------- */
  { kat: "ilmu", judul: "Memohon Tambahan Ilmu",
    ar: "رَبِّ زِدْنِي عِلْمًا",
    latin: "Rabbi zidni 'ilma.",
    arti: "Ya Tuhanku, tambahkanlah ilmu kepadaku.",
    sumber: "QS. Thaha: 114" },
  { kat: "ilmu", judul: "Ilmu yang Bermanfaat",
    ar: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا",
    latin: "Allahummanfa'ni bima 'allamtani wa 'allimni ma yanfa'uni wa zidni 'ilma.",
    arti: "Ya Allah, berilah aku manfaat dengan apa yang telah Engkau ajarkan kepadaku, ajarkanlah kepadaku apa yang bermanfaat bagiku, dan tambahkanlah ilmu kepadaku.",
    sumber: "HR. Tirmidzi dan Ibnu Majah" },
  { kat: "ilmu", judul: "Kelapangan Dada dan Kemudahan Urusan",
    ar: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    latin: "Rabbisyrah li shadri wa yassir li amri.",
    arti: "Ya Tuhanku, lapangkanlah dadaku dan mudahkanlah urusanku.",
    sumber: "QS. Thaha: 25-26",
    catatan: "Doa Nabi Musa, sering dibaca sebelum belajar, ujian, atau berbicara di depan orang." },
  { kat: "ilmu", judul: "Keteguhan Hati",
    ar: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
    latin: "Ya muqallibal-qulub, tsabbit qalbi 'ala dinik.",
    arti: "Wahai Zat yang membolak-balikkan hati, teguhkanlah hatiku di atas agama-Mu.",
    sumber: "HR. Tirmidzi" },
  { kat: "ilmu", judul: "Kebaikan Dunia dan Akhirat (Sapu Jagat)",
    ar: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    latin: "Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adzaban-nar.",
    arti: "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.",
    sumber: "QS. Al-Baqarah: 201" },

  /* ---------- Keluarga ---------- */
  { kat: "keluarga", judul: "Untuk Kedua Orang Tua",
    ar: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    latin: "Rabbir-hamhuma kama rabbayani shaghira.",
    arti: "Ya Tuhanku, sayangilah keduanya sebagaimana mereka berdua telah mendidikku pada waktu kecil.",
    sumber: "QS. Al-Isra': 24" },
  { kat: "keluarga", judul: "Ampunan untuk Orang Tua dan Mukminin",
    ar: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    latin: "Rabbanaghfir li wa liwalidayya wa lil-mu'minina yauma yaqumul-hisab.",
    arti: "Ya Tuhan kami, ampunilah aku, kedua orang tuaku, dan seluruh orang mukmin pada hari diadakan perhitungan (hari Kiamat).",
    sumber: "QS. Ibrahim: 41" },
  { kat: "keluarga", judul: "Keluarga yang Menyejukkan Hati",
    ar: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    latin: "Rabbana hab lana min azwajina wa dzurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama.",
    arti: "Ya Tuhan kami, anugerahkanlah kepada kami pasangan dan keturunan sebagai penyejuk hati kami, dan jadikanlah kami pemimpin bagi orang-orang yang bertakwa.",
    sumber: "QS. Al-Furqan: 74" },
  { kat: "keluarga", judul: "Untuk Orang yang Wafat",
    ar: "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ",
    latin: "Allahummaghfir lahu warhamhu wa 'afihi wa'fu 'anhu.",
    arti: "Ya Allah, ampunilah dia, rahmatilah dia, selamatkanlah dia, dan maafkanlah dia.",
    sumber: "HR. Muslim",
    catatan: "Untuk perempuan, gunakan “laha” dan “'anha”." },

  /* ---------- Taubat dan Ampunan ---------- */
  { kat: "ampunan", judul: "Doa Nabi Adam",
    ar: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
    latin: "Rabbana zhalamna anfusana wa il lam taghfir lana wa tarhamna lanakunanna minal-khasirin.",
    arti: "Ya Tuhan kami, kami telah menzalimi diri kami sendiri. Jika Engkau tidak mengampuni kami dan tidak memberi rahmat kepada kami, niscaya kami termasuk orang-orang yang rugi.",
    sumber: "QS. Al-A'raf: 23" },
  { kat: "ampunan", judul: "Sayyidul Istighfar",
    ar: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    latin: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastatha'tu, a'udzu bika min syarri ma shana'tu, abu'u laka bini'matika 'alayya, wa abu'u bidzanbi faghfir li, fa innahu la yaghfirudz-dzunuba illa anta.",
    arti: "Ya Allah, Engkau Tuhanku, tidak ada tuhan yang berhak disembah selain Engkau. Engkau menciptakanku dan aku adalah hamba-Mu. Aku berada di atas perjanjian dan janji-Mu semampuku. Aku berlindung kepada-Mu dari keburukan perbuatanku. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku, maka ampunilah aku, karena tidak ada yang dapat mengampuni dosa kecuali Engkau.",
    sumber: "HR. Bukhari" },

  /* ---------- Kesulitan dan Sakit ---------- */
  { kat: "kesulitan", judul: "Doa Nabi Yunus",
    ar: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    latin: "La ilaha illa anta subhanaka inni kuntu minazh-zhalimin.",
    arti: "Tidak ada tuhan selain Engkau. Mahasuci Engkau, sungguh aku termasuk orang-orang yang zalim.",
    sumber: "QS. Al-Anbiya': 87" },
  { kat: "kesulitan", judul: "Ketika Tertimpa Musibah",
    ar: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
    latin: "Inna lillahi wa inna ilaihi raji'un. Allahumma'jurni fi mushibati wakhlif li khairan minha.",
    arti: "Sesungguhnya kami milik Allah dan kepada-Nya kami kembali. Ya Allah, berilah aku pahala dalam musibahku dan gantilah dengan yang lebih baik darinya.",
    sumber: "QS. Al-Baqarah: 156 dan HR. Muslim" },
  { kat: "kesulitan", judul: "Memohon Pertolongan",
    ar: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ",
    latin: "Ya hayyu ya qayyum, birahmatika astaghits.",
    arti: "Wahai Yang Maha Hidup, wahai Yang Maha Mengurus makhluk-Nya, dengan rahmat-Mu aku memohon pertolongan.",
    sumber: "HR. Tirmidzi" },
  { kat: "kesulitan", judul: "Menjenguk atau Memohon Kesembuhan",
    ar: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ، اشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    latin: "Allahumma rabban-nas, adzhibil-ba's, isyfi antasy-syafi, la syifa'a illa syifa'uk, syifa'an la yughadiru saqama.",
    arti: "Ya Allah, Tuhan manusia, hilangkanlah penyakit ini. Sembuhkanlah, Engkaulah Maha Penyembuh. Tidak ada kesembuhan selain kesembuhan dari-Mu, kesembuhan yang tidak meninggalkan penyakit.",
    sumber: "HR. Bukhari dan Muslim" }
];
